### ISSUE TITLE
Change Toggle token simulation to another shortcut

### ISSUE THREAD

**Issue by benhoffmann** [philippfromme/bpmn-js-token-simulation-plugin#2]
Hey guys,

Cmd-T is already used for opening new tabs. Would be great if you could change the shortcut. 

Besides that, it's a great piece of work!

**Comment by StephenOTT** [comment]
ctl+cmd+T ?

**Comment by philippfromme** [comment]
Sh*t, I didn't realize that. Will fix it today! 😅

**Comment by benhoffmann** [comment]
Much better! 

But now the menu is triggered whenever I edit a label. It's not that much of a problem right now, but maybe you could tweak it further so that the shortcut behaves the same way like `s`, `h`and so on. 

![sep -21-2017 09-25-59](https://user-images.githubusercontent.com/17595149/30683867-4ccb734c-9eaf-11e7-8d01-c61b568e4c51.gif)

**Comment by philippfromme** [comment]
OMG I'm so stupid 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 😅 

I will change it ASAP!

**Comment by philippfromme** [comment]
Reopening...

**Comment by philippfromme** [comment]
Fixed and pushed to master. Key is the same but only toggles if you're not editing.
