### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by kropsi** [philippfromme/bpmn-js-token-simulation-plugin#7]
@philippfromme, I added your BPMN simulation plugin as a folder "bpmn-js-token-simulation-plugin" into "plugins" directory in Camunda Modeler (on Mac), but "Token Simulation" button doesn't seem to appear on the board as illustrated in your gif animation tutorial. I tried to restart modeller, but nothing seems to help. Do you have any hints?

**Comment by kropsi** [comment]
On macOS you have to create the plugins folder in this directoy: /Users/{USER_NAME}/Library/Application Support/camunda-modeler and copy your plugins here instead of Application directory

**Comment by philippfromme** [comment]
Sorry, I didn't reply. This information can also be found in the [documentation](https://github.com/camunda/camunda-modeler/tree/master/docs/plugins) of the Camunda Modeler.

**Comment by kropsi** [comment]
Yes, but it was not easy to find, so I suggest that you add a line to the README file. It will help many to install it faster. Thank you for a great plugin!
